FROM postgres:latest
ENV POSTGRES_PASSWORD=12345678
ENV POSTGRES_USER=kiri
ENV POSTGRES_DB=database
COPY db/init.sql /docker-entrypoint-initdb.d/init.sql
COPY db/request.sql /docker-entrypoint-initdb.d/request.sql
